### ISSUE TITLE
Consumer skips messages

### ISSUE THREAD

**Issue by rrruko** [rrruko/hs-kafka#15]
Currently, when we receive a fetch response, we update the offset on each partition to the value of the high_watermark field returned for that partition. This only works if the fetch response contains the latest unfetched message on the topic, since that is the message whose offset is at the high_watermark. The correct thing to do is something like getting the base_offset plus the last_offset_delta for each record batch, and then picking the greatest one out of all the batches in the set.

**Comment by chessai** [comment]
bruh!!!!!!

**Comment by rrruko** [comment]
da395d6 fixes this.

**Comment by chessai** [comment]
awesome thanks
