### ISSUE TITLE
Bad things lurk just around the corner

### ISSUE THREAD

**Issue by chessai** [rrruko/hs-kafka#16]
I notice in some places, for the sake of prototyping, you have something like

foo :: MutableReference a
foo = unsafePerformIO $ newMutableReference (bar :: a)

You need to add a NOINLINE pragma on these. If they inline, they could propagate throughout your program, duplicating effects. This is always the case for such top-level mutable references in haskell.

**Comment by rrruko** [comment]
67368a1

**Comment by chessai** [comment]
that wasn't necessary for the bytestring function, since it's not a mutable reference. however i tend to prefer http://hackage.haskell.org/package/file-embed for things like that
