### ISSUE TITLE
rename to `kafka`?

### ISSUE THREAD

**Issue by chessai** [rrruko/hs-kafka#3]
i own the `kafka` namespace on hackage, and i could make you a maintainer. i've been squatting it for when i eventually worked on my own client. you'd need to rename the library to `kafka`.

i don't think users will get confused about its status as a kafka client, because it obviously can't be a kafka server

**Comment by chessai** [comment]
you probably want to name the github repo itself as `hs-kafka` or `haskell-kafka` or something

**Comment by rrruko** [comment]
c8217f5
