### ISSUE TITLE
Remove all magic numbers

### ISSUE THREAD

**Issue by chessai** [rrruko/hs-kafka#5]
There are a bunch of inlined numeric constants here. They should be made top level, with descriptive names. They'll inline/constant fold so it shouldn't matter for perf

**Comment by rrruko** [comment]
Does this look good? 1c3b7b6 The magic numbers all just describe sizes of arrays (they are not things that have meaning in the kafka protocol) so I'm not sure it makes sense to make them top level.

**Comment by rrruko** [comment]
I made top-level definitions for the other constants where I had been passing 0 or -1.
